# Generated by Django 2.1.4 on 2019-01-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_semesterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='semesterdata',
            name='status',
        ),
        migrations.AddField(
            model_name='settingsdata',
            name='current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.SemesterData'),
        ),
    ]
