# Generated by Django 2.1.4 on 2019-01-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=30)),
                ('did', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.DepartmentData')),
                ('fid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.FacultyData')),
                ('sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.SessionData')),
            ],
        ),
    ]
